image:
  registry: docker.io
  repository: ojt90902/my-db-build
  tag: latest

tomcatAllowRemoteManagement: 1

persistence:
  enabled: false

service:
  type: NodePort
  nodePorts:
    http: 80

extraEnvVars:
  - name: JAVA_OPTS
    value: '-Dspring.profiles.active=dev'